#ifndef CLASS_DEFS
#define CLASS_DEFS

#define PI 3.14159

#define CHUNK_SIZE 8
#define CHUNK_SCALE 4
#define SCREEN_WIDTH_CHUNKS 16*2
#define SCREEN_HEIGHT_CHUNKS 15*2

#define FRAMERATE 30

#define PLAYER_FRAMES_IN_SET 9
#define PLAYER_BULLET_0_SPEED 4
#define PLAYER_MOVE_SPEED 4
#define PLAYER_JUMP_VEL 10
#define PLAYER_JUMP_TIMEOUT_MS 125
#define PLAYER_FALL_ACCEL 1
#define PLAYER_FALL_TERMINAL_VEL 8

#define RIPPER_MOVE_SPEED 1
#define ZOOMER_MOVE_SPEED 1

#endif // CLASS_DEFS
