#ifndef CLASS_DEFS
#define CLASS_DEFS

#define CHUNK_SIZE 8
#define CHUNK_SCALE 2
#define SCREEN_WIDTH_CHUNKS 16*2
#define SCREEN_HEIGHT_CHUNKS 15*2

#define FRAMERATE 30

#define PLAYER_FRAMES_IN_SET 8
#define PLAYER_MOVE_SPEED 5
#define PLAYER_JUMP_VEL 10
#define PLAYER_JUMP_TIMEOUT_MS 0
#define PLAYER_FALL_ACCEL 1
#define PLAYER_FALL_TERMINAL_VEL 7

#define RIPPER_MOVE_SPEED 1

#endif // CLASS_DEFS
